name: Daily Python Script Email

on:
  push:
    branches:
      - main
      - remove_duplicates # Replace this with your actual branch name
  schedule:
    - cron: "0 5 * * *" # Runs every day at 07:00 AM CET / 08:00 AM CEST
    - cron: "0 10 * * *" # Runs every day at 12:00 PM CET / 01:00 PM CEST
    - cron: "0 02 * * *" # Runs every day at 11:00 AM CET / 12:00 PM CEST
    - cron: "0 06 * * *" # Runs every day at 01:00 PM CET / 02:00 PM CEST

jobs:
  run-python-script-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        id: run_script
        run: |
          python jobs.py

      - name: Send Email
        run: |
          python send_email.py
        env:
          GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECIEVER_EMAIL }}
